# Generated by Django 5.0.6 on 2024-05-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0004_userinfor_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfor',
            name='role',
            field=models.IntegerField(default=1),
        ),
    ]
