# Generated by Django 5.0.6 on 2024-05-24 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0005_userinfor_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfor',
        ),
    ]
