# Generated by Django 5.0.6 on 2024-05-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfor',
        ),
    ]
