# Generated by Django 5.0.6 on 2024-05-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0010_userinfo_delete_finance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
