# Generated by Django 5.0.6 on 2024-06-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
