# Generated by Django 5.0.6 on 2024-06-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0014_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
