# Generated by Django 5.0.6 on 2024-06-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsApp', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
